# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- script:
    docker run -i --rm -v $(pwd):/usr/src/plasma -w /usr/src/plasma -e GOOS=js -e GOARCH=wasm golang:latest go build -o plasma.wasm plasma.go
  displayName: 'Build WASM'

- script: 
    docker run -i --rm -v $(pwd):/usr/src/plasma -w /usr/src/plasma golang:latest cp /usr/local/go/misc/wasm/wasm_exec.js /usr/src/plasma
  displayName: 'Copy current wasm_exec.js'

- script: |
    cp wasm_exec.js $(Build.ArtifactStagingDirectory)
    cp plasma.js $(Build.ArtifactStagingDirectory)
    cp plasma.wasm $(Build.ArtifactStagingDirectory)
    cp index.html $(Build.ArtifactStagingDirectory)
  workingDirectory: '$(modulePath)'
  displayName: 'Copy assets to aritfacts staging'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'plasmawasmgo'